/* Generated by Yosys 0.31+13 (git sha1 411b6e98c, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module manhattan_sequencedetector(sequence_in, clock, reset, detector_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input clock;
  wire clock;
  wire [2:0] current_state;
  output detector_out;
  wire detector_out;
  wire [2:0] next_state;
  input reset;
  wire reset;
  input sequence_in;
  wire sequence_in;
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor3b_1 _17_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C_N(current_state[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _18_ (
    .A(sequence_in),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3b_1 _19_ (
    .A_N(current_state[1]),
    .B(current_state[0]),
    .C(current_state[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__o22ai_1 _20_ (
    .A1(sequence_in),
    .A2(_05_),
    .B1(_07_),
    .B2(_04_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2b_1 _21_ (
    .A(current_state[2]),
    .B_N(current_state[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _22_ (
    .A(current_state[0]),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3b_1 _23_ (
    .A(current_state[1]),
    .B(current_state[2]),
    .C_N(current_state[0]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o31ai_1 _24_ (
    .A1(sequence_in),
    .A2(current_state[2]),
    .A3(_04_),
    .B1(_08_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__o21ai_0 _25_ (
    .A1(_05_),
    .A2(_11_),
    .B1(sequence_in),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _26_ (
    .A(sequence_in),
    .B(current_state[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(_09_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _28_ (
    .A(_12_),
    .B(_14_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__a21oi_1 _29_ (
    .A1(sequence_in),
    .A2(_10_),
    .B1(_06_),
    .Y(next_state[2])
  );
  sky130_fd_sc_hd__and3_1 _30_ (
    .A(sequence_in),
    .B(_00_),
    .C(_07_),
    .X(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clock),
    .D(_03_),
    .Q(detector_out)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clock),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clock),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clock),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(_02_)
  );
endmodule
